// questions.js

window.generalId = "ds";
window.quizId = "sd";

window.initialQuestions = [
  {
    id: "ds_sd_1",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "what is a Surgical Safety Checklist (SSC)?$$IMG$$img/fris_default2024-10-01_02-50-56.452.png$$/IMG$$",
    choices: [
      "A tool to reduce the risk of preventable complications at surgery.",
      "A list of equipment that will be required during the surgery.",
      "A tool to ensure that all staff in the practice are prepared for an emergency situation.",
      "A document listing all the roles of staff members in the operating theatre.",
      "A tool for reviewing surgery outcome and implementing improvements.",
    ],
    correctAnswers: [0],
    keywords: ["Surgical", "Checklist"],
    tags: ["nan"],
    note: '<br><div class="container" style="width: 100%;<br>max-width: 1200px;<br>margin: 0 auto"><br><h1 style="color: #2c3e50;<br>text-align: center">حالة Severe Preeclampsia</h1><br><p>بص يا سيدي، المريضة دي عندها <span class="important" style="color: #e74c3c;<br>font-weight: bold">severe preeclampsia</span>. عشان نوضح ليه، خلينا نمشي خطوة بخطوة.</p><br><h2 style="color: #3498db">1) ليه ده الاختيار الصح؟</h2><br><ul style="list-style-type: none;<br>padding-right: 20px"><br><li>المريضة عندها <span class="highlight" style="background-color: #ffeaa7;<br>padding: 2px 4px;<br>border-radius: 3px">ضغط دم عالي جدًا 170/100 mmHg</span>.</li><br><li>عندها <span class="highlight" style="background-color: #ffeaa7;<br>padding: 2px 4px;<br>border-radius: 3px">headache (صداع)، epigastric pain (ألم في منطقة المعدة)، وvisual abnormalities (مشاكل في الرؤية)</span>.</li><br><li>وفيه <span class="highlight" style="background-color: #ffeaa7;<br>padding: 2px 4px;<br>border-radius: 3px">+3 proteinuria (بروتين في البول بمقدار +3)</span>.</li><br></ul><br><p>كل دي علامات تدل على <span class="important" style="color: #e74c3c;<br>font-weight: bold">severe preeclampsia</span>. أخطر حاجة ممكن تحصل في الحالة دي هي إنها تدخل في <span class="important" style="color: #e74c3c;<br>font-weight: bold">eclampsia</span> يعني يحصلها <span class="highlight" style="background-color: #ffeaa7;<br>padding: 2px 4px;<br>border-radius: 3px">seizures (تشنجات)</span>. علشان كده، أول حاجة لازم نعملها إننا نبتدي <span class="important" style="color: #e74c3c;<br>font-weight: bold">magnesium sulfate intravenously</span> لمنع التشنجات.</p><br><h2 style="color: #3498db">2) ليه الباقي غلط؟</h2><br><ul style="list-style-type: none;<br>padding-right: 20px"><br><li><strong>Perform an emergency C-section:</strong> مش بنعمل C-section طوارئ إلا لو في خطر على الجنين أو الأم لا قدر الله. لكن البيوفيزيكال بروفايل بتاع الجنين 8/8، يعني الجنين بخير حاليًا.</li><br><li><strong>Give betamethasone to induce fetal lung maturity:</strong> الـbetamethasone بنديه عشان نساعد في نضج رئة الجنين لو العمر الحملي أقل من 34 weeks. لكن المريضة دي في 34 weeks، وفي السن دا الرئة بتكون تقريبًا نضجت.</li><br><li><strong>Perform an amniocentesis to assess fetal lung maturity:</strong> الـamniocentesis إجراء تدخل جراحي بسيط ناخد بيه عينة من السائل الأمينوسي، ومش هيفيدنا دلوقتي لأن العمر الحملي مناسب، وكمان الجنين حالته كويسة.</li><br><li><strong>Repeat the biophysical profile daily:</strong> مفيش داعي نكرره يوميًا طالما الجنين حالته مستقرة. المشكلة الأساسية دلوقتي هي حالة الأم، ولازم نمنع تطور الحالة لـeclampsia.</li><br></ul><br><h2 style="color: #3498db">3) إيه الكلمات المفتاحية في رأس السؤال اللي عرفتك كده؟</h2><br><ul style="list-style-type: none;<br>padding-right: 20px"><br><li><strong>Blood pressure of 170/100 mmHg:</strong> ضغط دم عالي جدًا.</li><br><li><strong>Headache, epigastric pain, visual abnormalities:</strong> أعراض تشير لـsevere preeclampsia.</li><br><li><strong>+3 proteinuria:</strong> نسبة بروتين عالية في البول، علامة تانية على الـpreeclampsia.</li><br><li><strong>Biophysical profile of the fetus is 8/8:</strong> الجنين حالته ممتازة، مفيش قلق عليه دلوقتي.</li><br></ul><br><p>كل الحاجات دي بتقول إن المريضة عندها <span class="important" style="color: #e74c3c;<br>font-weight: bold">severe preeclampsia</span>، ولازم نبتدي <span class="important" style="color: #e74c3c;<br>font-weight: bold">magnesium sulfate intravenously</span> فورًا لمنع التشنجات وحماية الأم والجنين.</p><br></div><br>',
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_2",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "How can the traditional surgical culture help improve safety in the operation theatre?",
    choices: [
      "Surgeon in-charge being responsible for the final outcome (hierarchical structure).",
      "Monthly morbidity and mortality conference discussion of various problems.",
      "Identification of the problem and the ability to solve when it occurs.",
      "The ability to work under stressful condition.",
    ],
    correctAnswers: [3],
    keywords: ["traditional"],
    tags: ["nan"],
    note: "The senior surgeon should be able to able to identify any problem and share his pinion with his team. Once the problem is clearly identified, solution of the problem is performed in a systematic calm manner.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_3",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "What is the most common cause of choosing the wrong side of surgery?",
    choices: [
      "Poor communication.",
      "Unavailable information at the time of procedure.",
      "Poor training of the team.",
      "None of the above.",
    ],
    correctAnswers: [0],
    keywords: ["nan"],
    tags: ["nan"],
    note: "Good communication is a vital component of team work and should be strictly adopted in any organization wishing to achieve maximum patient safety.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_4",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "Within six minutes of starting blood transfusion, the patient complains of headache, chest and back pain, as well as dyspnea. What is the main line of treatment?",
    choices: [
      "Endotracheal intubation and mechanical ventilation.",
      "Fluid restriction.",
      "IV opioid analgesic.",
      "IV hydrocortisone.",
      "Fluids and mannitol.",
    ],
    correctAnswers: [4],
    keywords: ["six", "headache"],
    tags: ["nan"],
    note: "This is an immediate haemolytic transfusion reaction, which presents after the administration of less than 50ml. The patient may also have fever and chills. Oliguria and smoky red urine would show if the patient has a urinary catheter. The first step is to discontinue blood and give IV fluids and mannitol to flush the renal tubules and prevent renal failure. Diagnosis is more difficult if the patient is under anaesthesia. The condition is suspected when the surgeon observes unexplained excessive bleeding.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_5",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "About pseudomembranous colitis, one statement only is true.",
    choices: [
      "Is caused by overgrowth of Clostridium perfringes.",
      "Is a common cause of colon perforation.",
      "Responds to treatment with vancomycin.",
      "Metronidazole administration is the usual cause.",
      "Clindamycin is added for the treatment of severe cases.",
    ],
    correctAnswers: [2],
    keywords: ["nan"],
    tags: ["nan"],
    note: "Pseudomembranous colitis, also known as antibiotic-associated colitis, is a serious condition that is caused by the administration of antibiotics that kill colonic commensals and lead to overgrowth of Clostridium difficile. Patients present with watery diarrhoea, fever, abdominal pain and, in some cases, rectal bleeding. Clindamycin is the antibiotic classically accused as the causative agent, but any antibiotic can be the cause. Treatment of this condition includes discontinuation of the offending antibiotic and the administration metronidazole or vancomycin, together with IV fluid replacement of losses.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_6",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "A 15-year-old boy refuses to have a necessary emergency surgery for what is diagnosed as ruptured appendix. What is the legal solution?",
    choices: [
      "Wait until the patient is convinced enough to give a consent.",
      "Get consent from one of the parents.",
      "Get a court order.",
      "Get two qualified surgeons to examine the boy and sign a statement stressing the necessity of urgent surgery.",
      "Proceed to emergency surgery without any of the above.",
    ],
    correctAnswers: [1],
    keywords: ["nan"],
    tags: ["nan"],
    note: "A patient is not competent enough to sign a consent until he is 18. One of the parents should sign the consent.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_7",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "A 29-year-old man is shot in the abdomen. On arrival to hospital he is in hypovolaemic shock and is unconscious. He is not accompanied by any family members. A resident surgeon decides that emergency laparotomy is indicated to save his life. What is the legal solution to provision of consent?",
    choices: [
      "Resuscitate and wait until the patient is conscious enough to provide an informed consent.",
      "A qualified surgeon (if available two surgeons) should examine and provides a signed statement for the necessity of urgent surgery.",
      "Get approval for surgery from the hospital's legal department.",
      "Get an emergency court order for emergency surgery.",
      "Proceed to emergency surgery without any of the above.",
    ],
    correctAnswers: [1],
    keywords: ["nan"],
    tags: ["nan"],
    note: "Residency is a training period. A qualified surgeon, or better still two qualified surgeons, should be the one to sign a statement for the necessity of urgent surgery before proceeding to the operating room.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_8",
    generalId: "ds",
    quizId: "sd",
    category: "Safety of Patient",
    text: "In the recovery room after laparoscopic cholecystectomy a 37-year old woman is observed to have a burn in her left thigh. The cause is most likely to be",
    choices: [
      "Allergic reaction to the anesthetic agent.",
      "Hypersensitivity reaction to the adhesive tape.",
      "Direct application of active electrocautery blade to the left thigh.",
      "An abscess at the site of IM injection of prophylactic antibiotic.",
      "None of the above.",
    ],
    correctAnswers: [4],
    keywords: ["nan"],
    tags: ["nan"],
    note: "The most probable cause is improper application of electrocautery grounding pad.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_9",
    generalId: "ds",
    quizId: "sd",
    category: "Surgery in  Elderly",
    text: "What is the most common change in the kidney in the elderly population?",
    choices: [
      "Increased filtration rate.",
      "Decreased serum creatinine.",
      "Decreased glomenrular filtration rate.",
      "Increased filtration area.",
    ],
    correctAnswers: [2],
    keywords: ["nan"],
    tags: ["nan"],
    note: "Surgery in the elderly, which is also called geriatric surgery, is difficult to define. The age limit is increasing, but for the time being, the American College of Surgeons define it as surgery for those at 65 years or more. With age, the size and volume of the kidney decrease. There is decrease in the nephron mass as well as the number of glomeruli. This results in reduction of the glomerular filtration rate. Furthermore, reduction of the cardiac output with age, reduces renal blood flow and further reduces the glomerular filtration rate.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_10",
    generalId: "ds",
    quizId: "sd",
    category: "Surgery in  Elderly",
    text: "What is the most common valvular surgery in the elderly?",
    choices: [
      "Aortic incompetency.",
      "Aortic stenosis.",
      "Tricuspid stenosis.",
      "Mitral incompetence.",
    ],
    correctAnswers: [1],
    keywords: ["nan"],
    tags: ["nan"],
    note: "The most common valvular disease in the elderly is calcific aortic stenosis. This could present with syncope and angina. Investigation of the carotid system and coronary angiogram is mandatory before surgery. The mortality rate after aortic valve replacement alone is about 3-5%.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_11",
    generalId: "ds",
    quizId: "sd",
    category: "Surgery in  Elderly",
    text: "The following are strong predictors of adverse cardiac outcomes of surgery, except",
    choices: [
      "Recent myocardial infarction.",
      "Uncompensated congestive heart failure.",
      "Unstable ischemic heart disease.",
      "Age above 65.",
      "Major and emergency surgery.",
    ],
    correctAnswers: [3],
    keywords: ["nan"],
    tags: ["nan"],
    note: "Age, in itself, is a minor risk factor. The strongest predictors of adverse cardiac outcomes are recent myocardial infarction, uncompensated congestive heart failure, unstable ischemic heart disease, and sever arhythmia. Major and emergency surgery are certainly more serious than minor and elective ones.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_12",
    generalId: "ds",
    quizId: "sd",
    category: "Surgery in  Elderly",
    text: "Surgery in the elderly (geriatric surgery) is characterized by the following",
    choices: [
      "Clinical presentation may by milder than usual.",
      "They handle severe stress poorly.",
      "Cognetive disabilities affect patient's cooperation.",
      "All of the above.",
      "None of the above.",
    ],
    correctAnswers: [3],
    keywords: ["nan"],
    tags: ["nan"],
    note: "In the geriatric age group, the presentation of surgical problems may be milder or different from that of the younger population. This may lead to delays in diagnosis. In appendicitis, for example, a classic presentation occurs in less than one-third of elderly patients, resulting in about 50% incidence of perforation. In addition, elderly patients handle severe stress poorly because of poor system reserve.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_13",
    generalId: "ds",
    quizId: "sd",
    category: "Surgery in  Elderly",
    text: "An elderly is likely to suffer a higher incidence of all the following, except",
    choices: [
      "Intraoperative excessive bleeding.",
      "Postoperative deep vein thrombosis.",
      "Postoperative delirium.",
      "Postoperative pneumonia.",
      "Postoperative myocardial infarction",
    ],
    correctAnswers: [0],
    keywords: ["nan"],
    tags: ["nan"],
    note: "Increasing age does not interfere with natural haemostatic abilities. Weaknes and associated recumbency predispose to postoperative DVT and pneumonia. Delirium is a common postoperative problem in the elderly. The use of opioid analgesic and tranquillizers should be limited.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_14",
    generalId: "ds",
    quizId: "sd",
    category: "Palliative Care in",
    text: "What is the initial treatment of dyspnea in a terminal patient?",
    choices: ["Opioids.", "Warming the room.", "Sedatives.", "Oxygen mask."],
    correctAnswers: [0],
    keywords: ["nan"],
    tags: ["nan"],
    note: "The primary treatment of a dying patient with dyspnea is opioids administration, and it should be very cautiously titrated. This decreases tachypnea and increases comfort. 02 nasal cannula can also be of help (3L/min). The 02 given should be humidified to avoid dry mouth and pharynx.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_15",
    generalId: "ds",
    quizId: "sd",
    category: "Palliative Care in",
    text: "What is the expected life span in a cancer patient sleeping more than 12 hours daily and requiring assistance in less than normal daily activities?",
    choices: ["Months.", "Weeks.", "Days.", "None of the above."],
    correctAnswers: [1],
    keywords: ["nan"],
    tags: ["nan"],
    note: "The patients who have advanced cancer disease requiring help and assistance in less than ordinary activities and sleeping more than 12 hours a day probably will not live longer than few weeks.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_16",
    generalId: "ds",
    quizId: "sd",
    category: "Palliative Care in",
    text: "A terminally ill patient with severe pain not controlled on maximum dose ( I 5mg/hr) of morphine, but 20 mg/hr of morphine could control the pain. There is a danger of respiratory depression, how to proceed?",
    choices: [
      "Continue on the same dose and add anxiolytic agents.",
      "Keep patient on 20 mg/hr.",
      "Bolus morphine addition.",
      "None of the above.",
    ],
    correctAnswers: [1],
    keywords: ["nan"],
    tags: ["nan"],
    note: "The aim of treatment in a terminally ill patient is to improve the quality of life and not to prolong it, so increasing the dose to 20 mg/hr will be aiming at decreasing the pain to minimum, meanwhile watching for respiratory depression.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_17",
    generalId: "ds",
    quizId: "sd",
    category: "Trauma",
    text: "For the trauma victim, one of the following is an indication for endotracheal intubation.",
    choices: [
      "Haemothorax.",
      "Open pneumothorax.",
      "Tension pneumothorax.",
      "Single rib fracture.",
      "Unconsciousness.",
    ],
    correctAnswers: [4],
    keywords: ["nan"],
    tags: ["nan"],
    note: "Haemo and pneumothoraces are indications for drainage of the pleural cavity by a chest tube. Unconscious trauma victims require intubation because they are unable to maintain a clear airway. This is actually the commonest indication of intubation for these patients. Other indications for intubation are stridor, flail chest and expanding haematoma or surgical emphysema of the neck. The latter two carry a risk of impending airway obstruction.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_18",
    generalId: "ds",
    quizId: "sd",
    category: "Trauma",
    text: "One of the following is an indicator of severe trauma that is likely to be associated with multiple injuries.",
    choices: [
      "Fracture of the sternum.",
      "Fracture of the tenth rib.",
      "Extradural haematoma.",
      "Facial lacerations.",
      "Fracture of the clavicle.",
    ],
    correctAnswers: [0],
    keywords: ["nan"],
    tags: ["nan"],
    note: "The following are indicators of severe trauma that is likely to be associated with multiple injuries. • Type of trauma, e.g. high-speed collision or fall from a height. • Circumstances of the accident, e.g., death of an accompanying car passenger. • Fracture of a sturdy bone, e.g., sternum, first rib or scapula.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_19",
    generalId: "ds",
    quizId: "sd",
    category: "Trauma",
    text: "A 23-year-old man is brought to the emergency room half an hour after being shot in the centre of the abdomen by a gun. He is irritable, pale and sweating. His pulse is 142/minute and his blood pressure is 75/30mmHg. The proper management is:",
    choices: [
      "Urgently shifting patient to the operating room for laparotomy, while resuscitating on the way.",
      "Urgent CT scan of the abdomen to diagnose injuries, then surgery.",
      "Urgent ultrasound of the abdomen to diagnose injuries, then surgery.",
      "Resuscitation of the patient in intensive care unit, then laparotomy when he becomes haemodynamically stable.",
      "Immediate transfer to a specialized trauma centre.",
    ],
    correctAnswers: [0],
    keywords: ["nan"],
    tags: ["nan"],
    note: "This patient is in hypovolaemic shock because of severe intra-abdominal bleeding. Arrest of bleeding by urgent surgery is the only way to save his life. Time should not be wasted in imaging, transfer to another hospital or prolonged futile attempts at resuscitation before surgery.",
    userAnswer: [],
    showingNote: false,
  },
  {
    id: "ds_sd_20",
    generalId: "ds",
    quizId: "sd",
    category: "Trauma",
    text: "A 26-year-old woman was brought to the emergency room after being stabbed in the left parasternal area. She is irritable but is breathing easily. Her blood pressure is 80/40mmHg and her pulse rate is 136/minute. Here neck veins are congested. The most probable diagnosis is",
    choices: [
      "Haemothorax.",
      "Open pneumothorax.",
      "Haemopneumothorax.",
      "Cardiac tamponade.",
      "Tension pneumothorax.",
    ],
    correctAnswers: [3],
    keywords: ["nan"],
    tags: ["nan"],
    note: "A shocked trauma victim with congested neck veins means either tension pneumothorax or cardiac tamponade (blood in the pericardial sac). One can differentiate between them at a glance by looking for dyspnea. Tension pneumothorax patients have marked dyspnea (then find out its other manifestations as deviated trachea and bulging tympanitic one side of the chest), while tamponade patients should be breathing easily. For cardiac tamponade do not send the patients to radiology room for diagnosis. Patients should have immediate evacuation of blood by inserting a cannula in pericardium. This is followed by IV fluids (despite high CVP), while taking them to the operating room for median sternotomy in order to stop bleeding.",
    userAnswer: [],
    showingNote: false,
  },
];

if (!window.allQuestions) window.allQuestions = [];
window.allQuestions = window.allQuestions.concat(window.initialQuestions);
